name: gradle
adopt-info: gradle

base: core22
grade: stable
confinement: classic
compression: lzo

summary: An open-source build automation tool
license: Apache-2.0
description: |
  Gradle is a build tool with a focus on build automation and support for
  multi-language development. If you are building, testing, publishing, and
  deploying software on any platform, Gradle offers a flexible model that can
  support the entire development lifecycle from compiling and packaging code to
  publishing web sites. Gradle has been designed to support build automation
  across multiple languages and platforms including Java, Scala, Android, C/C++,
  and Groovy, and is closely integrated with development tools and continuous
  integration servers including Eclipse, IntelliJ, and Jenkins.

apps:
  gradle:
    command: cli.sh
    environment:
      LANG: C.UTF-8
      LANGUAGE: C.UTF-8
      LC_ALL: C.UTF-8
      SNAP_JAVA_HOME: $SNAP/usr/lib/jvm/java-1.21.0-openjdk-$SNAP_ARCH
      SNAP_GRADLE_USER_HOME: /home/$USER/.gradle

parts:
  java:
    plugin: nil
    build-attributes:
      - enable-patchelf
    build-packages:
      - openjdk-21-jdk-headless
    stage-packages:
      - openjdk-21-jdk-headless
    override-build: |
      JAVA_HOME="$(dirname $(dirname $(readlink -f $(which java))))"
      cp -f /etc/ssl/certs/java/cacerts ${CRAFT_PART_INSTALL}/${JAVA_HOME}/lib/security/cacerts
      chmod 644 ${CRAFT_PART_INSTALL}/${JAVA_HOME}/lib/security/cacerts
      craftctl default

  gradle:
    after: [java]
    plugin: nil
    source: https://services.gradle.org/distributions/gradle-8.14.2-bin.zip
    override-build: |
      version=$($SNAPCRAFT_PART_SRC/gradle-*/bin/gradle -qv|awk '/Gradle/{print $2}')

      snapcraftctl set-version $version
      snapcraftctl build

      mkdir -p $SNAPCRAFT_PART_INSTALL/opt
      mv $SNAPCRAFT_PART_BUILD/gradle-* $SNAPCRAFT_PART_INSTALL/opt/gradle

  launcher:
    plugin: nil
    source: .
    override-build: |
      cp cli.sh ${CRAFT_PART_INSTALL}/
      craftctl default
