name: gradle
adopt-info: gradle

base: core20
grade: stable
confinement: classic
compression: lzo

summary: An open-source build automation tool
license: Apache-2.0
description: |
  Gradle is a build tool with a focus on build automation and support for
  multi-language development. If you are building, testing, publishing, and
  deploying software on any platform, Gradle offers a flexible model that can
  support the entire development lifecycle from compiling and packaging code to
  publishing web sites. Gradle has been designed to support build automation
  across multiple languages and platforms including Java, Scala, Android, C/C++,
  and Groovy, and is closely integrated with development tools and continuous
  integration servers including Eclipse, IntelliJ, and Jenkins.

apps:
  gradle:
    command: opt/gradle/bin/gradle
    environment:
      LANG: C.UTF-8
      LANGUAGE: C.UTF-8
      LC_ALL: C.UTF-8
      JAVA_HOME: $SNAP/usr/lib/jvm/default-java
      GRADLE_USER_HOME: /home/$USER/.gradle

parts:
  java:
    plugin: nil
    build-packages:
      - openjdk-16-jdk-headless
    stage-packages:
      - openjdk-16-jdk-headless
    override-build: |
      rm $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-16-openjdk-${SNAPCRAFT_TARGET_ARCH}/lib/security/cacerts
      cp /etc/default/cacerts $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-16-openjdk-${SNAPCRAFT_TARGET_ARCH}/lib/security/cacerts

  gradle:
    after: [java]
    plugin: nil
    source: https://services.gradle.org/distributions/gradle-7.1-bin.zip
    override-build: |
      version=$($SNAPCRAFT_PART_SRC/gradle-*/bin/gradle -qv|awk '/Gradle/{print $2}')

      snapcraftctl set-version $version
      snapcraftctl build

      mkdir -p $SNAPCRAFT_PART_INSTALL/opt
      mv $SNAPCRAFT_PART_BUILD/gradle-* $SNAPCRAFT_PART_INSTALL/opt/gradle
